/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as QaRouteImport } from './routes/qa'
import { Route as LensesRouteImport } from './routes/lenses'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as ProductSoleneRouteImport } from './routes/product.solene'
import { Route as ProductMeridianRouteImport } from './routes/product.meridian'
import { Route as ProductMaraisRouteImport } from './routes/product.marais'
import { Route as ProductAtelierRouteImport } from './routes/product.atelier'
import { Route as LocaleWomenRouteImport } from './routes/$locale.women'
import { Route as LocaleTechnologyRouteImport } from './routes/$locale.technology'
import { Route as LocaleMenRouteImport } from './routes/$locale.men'
import { Route as LocaleKidsRouteImport } from './routes/$locale.kids'
import { Route as LocaleFaqRouteImport } from './routes/$locale.faq'
import { Route as LocaleContactRouteImport } from './routes/$locale.contact'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const LensesRoute = LensesRouteImport.update({
  id: '/lenses',
  path: '/lenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const ProductSoleneRoute = ProductSoleneRouteImport.update({
  id: '/product/solene',
  path: '/product/solene',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductMeridianRoute = ProductMeridianRouteImport.update({
  id: '/product/meridian',
  path: '/product/meridian',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductMaraisRoute = ProductMaraisRouteImport.update({
  id: '/product/marais',
  path: '/product/marais',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductAtelierRoute = ProductAtelierRouteImport.update({
  id: '/product/atelier',
  path: '/product/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWomenRoute = LocaleWomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTechnologyRoute = LocaleTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMenRoute = LocaleMenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleKidsRoute = LocaleKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFaqRoute = LocaleFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/lenses': typeof LensesRoute
  '/qa': typeof QaRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technology': typeof TechnologyRoute
  '/warranty': typeof WarrantyRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/kids': typeof LocaleKidsRoute
  '/$locale/men': typeof LocaleMenRoute
  '/$locale/technology': typeof LocaleTechnologyRoute
  '/$locale/women': typeof LocaleWomenRoute
  '/product/atelier': typeof ProductAtelierRoute
  '/product/marais': typeof ProductMaraisRoute
  '/product/meridian': typeof ProductMeridianRoute
  '/product/solene': typeof ProductSoleneRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/lenses': typeof LensesRoute
  '/qa': typeof QaRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technology': typeof TechnologyRoute
  '/warranty': typeof WarrantyRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/kids': typeof LocaleKidsRoute
  '/$locale/men': typeof LocaleMenRoute
  '/$locale/technology': typeof LocaleTechnologyRoute
  '/$locale/women': typeof LocaleWomenRoute
  '/product/atelier': typeof ProductAtelierRoute
  '/product/marais': typeof ProductMaraisRoute
  '/product/meridian': typeof ProductMeridianRoute
  '/product/solene': typeof ProductSoleneRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/lenses': typeof LensesRoute
  '/qa': typeof QaRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technology': typeof TechnologyRoute
  '/warranty': typeof WarrantyRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/kids': typeof LocaleKidsRoute
  '/$locale/men': typeof LocaleMenRoute
  '/$locale/technology': typeof LocaleTechnologyRoute
  '/$locale/women': typeof LocaleWomenRoute
  '/product/atelier': typeof ProductAtelierRoute
  '/product/marais': typeof ProductMaraisRoute
  '/product/meridian': typeof ProductMeridianRoute
  '/product/solene': typeof ProductSoleneRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/contact'
    | '/faq'
    | '/lenses'
    | '/qa'
    | '/shipping'
    | '/sitemap.xml'
    | '/technology'
    | '/warranty'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/faq'
    | '/$locale/kids'
    | '/$locale/men'
    | '/$locale/technology'
    | '/$locale/women'
    | '/product/atelier'
    | '/product/marais'
    | '/product/meridian'
    | '/product/solene'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/lenses'
    | '/qa'
    | '/shipping'
    | '/sitemap.xml'
    | '/technology'
    | '/warranty'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/faq'
    | '/$locale/kids'
    | '/$locale/men'
    | '/$locale/technology'
    | '/$locale/women'
    | '/product/atelier'
    | '/product/marais'
    | '/product/meridian'
    | '/product/solene'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/contact'
    | '/faq'
    | '/lenses'
    | '/qa'
    | '/shipping'
    | '/sitemap.xml'
    | '/technology'
    | '/warranty'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/faq'
    | '/$locale/kids'
    | '/$locale/men'
    | '/$locale/technology'
    | '/$locale/women'
    | '/product/atelier'
    | '/product/marais'
    | '/product/meridian'
    | '/product/solene'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LensesRoute: typeof LensesRoute
  QaRoute: typeof QaRoute
  ShippingRoute: typeof ShippingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TechnologyRoute: typeof TechnologyRoute
  WarrantyRoute: typeof WarrantyRoute
  ProductAtelierRoute: typeof ProductAtelierRoute
  ProductMaraisRoute: typeof ProductMaraisRoute
  ProductMeridianRoute: typeof ProductMeridianRoute
  ProductSoleneRoute: typeof ProductSoleneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenses': {
      id: '/lenses'
      path: '/lenses'
      fullPath: '/lenses'
      preLoaderRoute: typeof LensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/product/solene': {
      id: '/product/solene'
      path: '/product/solene'
      fullPath: '/product/solene'
      preLoaderRoute: typeof ProductSoleneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/meridian': {
      id: '/product/meridian'
      path: '/product/meridian'
      fullPath: '/product/meridian'
      preLoaderRoute: typeof ProductMeridianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/marais': {
      id: '/product/marais'
      path: '/product/marais'
      fullPath: '/product/marais'
      preLoaderRoute: typeof ProductMaraisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/atelier': {
      id: '/product/atelier'
      path: '/product/atelier'
      fullPath: '/product/atelier'
      preLoaderRoute: typeof ProductAtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/women': {
      id: '/$locale/women'
      path: '/women'
      fullPath: '/$locale/women'
      preLoaderRoute: typeof LocaleWomenRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/technology': {
      id: '/$locale/technology'
      path: '/technology'
      fullPath: '/$locale/technology'
      preLoaderRoute: typeof LocaleTechnologyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/men': {
      id: '/$locale/men'
      path: '/men'
      fullPath: '/$locale/men'
      preLoaderRoute: typeof LocaleMenRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/kids': {
      id: '/$locale/kids'
      path: '/kids'
      fullPath: '/$locale/kids'
      preLoaderRoute: typeof LocaleKidsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/faq': {
      id: '/$locale/faq'
      path: '/faq'
      fullPath: '/$locale/faq'
      preLoaderRoute: typeof LocaleFaqRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleFaqRoute: typeof LocaleFaqRoute
  LocaleKidsRoute: typeof LocaleKidsRoute
  LocaleMenRoute: typeof LocaleMenRoute
  LocaleTechnologyRoute: typeof LocaleTechnologyRoute
  LocaleWomenRoute: typeof LocaleWomenRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleFaqRoute: LocaleFaqRoute,
  LocaleKidsRoute: LocaleKidsRoute,
  LocaleMenRoute: LocaleMenRoute,
  LocaleTechnologyRoute: LocaleTechnologyRoute,
  LocaleWomenRoute: LocaleWomenRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LensesRoute: LensesRoute,
  QaRoute: QaRoute,
  ShippingRoute: ShippingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TechnologyRoute: TechnologyRoute,
  WarrantyRoute: WarrantyRoute,
  ProductAtelierRoute: ProductAtelierRoute,
  ProductMaraisRoute: ProductMaraisRoute,
  ProductMeridianRoute: ProductMeridianRoute,
  ProductSoleneRoute: ProductSoleneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
